server:
  address: "0.0.0.0:8080"
  rounds: 3
  min_clients: 2

clients:
  total: 2
  batch_size: 64      # Batch size for all clients
  local_epochs: 1     # Clients train for 1 full epoch on their data
  learning_rate: 0.01

data:
  path: "./data"
  dataset: "MNIST"

attacks:
  gradient_inversion:
    enable: true     # <-- ATTACK IS DISABLED
    target_client: 1
    type: "dlg"
    client_lr: 0.01
    attack_lr: 0.01
    iterations: 5000

  model_poisoning:
    enable: false
    malicious_clients: [2]
    type: "scaling"  # "noise", "sign_flip", or "scaling"

  data_poisoning:
    enable: false
    malicious_clients: [2]
    target_label: 0

  backdoor:
    enable: false
    malicious_clients: [2]
    target_label: 0