server:
  address: "0.0.0.0:8080"
  rounds: 3
  min_clients: 2

clients:
  total: 2
  batch_size: 64      # Batch size for all clients
  local_epochs: 1     # Clients train for 1 full epoch on their data
  learning_rate: 0.01

data:
  path: "./data"
  dataset: "MNIST"

attacks:
  gradient_inversion:
    enable: false     # <-- ATTACK IS DISABLED
    target_client: 1
    type: "mdlg"   # <-- mdlg, dlg (actually idlg)
    client_lr: 0.01
    attack_lr: 0.01
    iterations: 5000

  model_poisoning:
    enable: false
    malicious_clients: [2] # Client 2 will be the attacker
    type: "scaling"        # Can be "scaling", "sign_flip", or "noise"
    scale_factor: -2.0     # Used only for "scaling" attack
    noise_scale: 0.5       # Used only for "noise" attack

  data_poisoning:
    enable: true
    malicious_clients: [2]
    target_label: 7        # The label to which poisoned images will be flipped
    poison_frac: 0.5       # Poison 50% of the malicious client's data